source_bucket: 'pyspark-trp'
aws_access_key_id : 'AKIA2GXT73H7EPUAFWF6'
aws_secret_access_key : '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'
s3_key: 'Manish_2022_data.csv'
local_csv_path: 'C:/Users/manissharma/Downloads/Pyspark-TRP/shared/2022_data.csv'